### ISSUE TITLE
--no-optional-dependencies not working as expected

### ISSUE THREAD

**Issue by http417** [claudiajs/claudia#216] opened 2020-04-22 03:11 UTC
Please use GitHub issues only to report bugs. To ask a general question or request assistance/support, please use the [Claudia.js Gitter Chat](https://gitter.im/claudiajs/claudia) instead.

To report a bug or a problem, please fill in the sections below. The more you provide, the better we'll be able to help.

---

* Expected behaviour:
optional dependencies such as aws-sdk are not included in zip

* What actually happens:
aws-sdk is included.
* Link to a minimal, executable project that demonstrates the problem:

* Steps to install the project:
install aws-sdk as optional dependency `npm i -O aws-sdk`
* Steps to reproduce the problem:
`claudia update --no-optional-dependencies`

* Please note 
it appears that claudia packages with the following npm command:
`npm install -q --no-package-lock --no-audit --production --no-optional`

if I remove the --no-package-lock option, then the optional dependencies are correctly omitted.

**Comment by jugglingcats** [comment] 2020-10-14 20:10
Related to #82. Would be nice to get a fix for this.

**Comment by jugglingcats** [comment] 2020-10-14 21:30
Possibly an npm version issue or something else in local environment. Have just looked at the package created as part of deployment (using Github action) and it doesn't contain aws-sdk! Maybe a Windows issue?

**Comment by danomatic** [comment] 2021-04-18 21:05
After battling this for hours today, I THINK the issue is the `npm dedupe`.  You can reproduce with:

```
rm -rf package-lock.json node_modules
npm install --no-optional --production
```
At this point `aws-sdk` is not installed
```
npm dedupe --no-optional --production
```
Still not installed
```
npm dedupe
```
Now it's installed

Running `claudia update` with ` --no-optional-dependencies`  does not apply `--no-optional --production` when running  `npm dedupe`

This is a total blocker for me. The size of the bundle is so large that my deploys are failing now.

**Comment by danomatic** [comment] 2021-04-18 21:28
^ this is with latest Node (14). Downgrading to 13, my `claudia update` no longer fails due to size (from aws-sdk and others).

**Comment by danomatic** [comment] 2021-05-02 10:43
More specifically, it's NPM 7 where Claudia has the issue with `dedupe`. It should be fixed to add the `--no-optional --production` flags. In the meantime, the workaround is to install NPM 6:

```
npm install -g npm@^6
```

**Comment by lehno** [comment] 2021-05-12 10:51
Any resolution on this?

**Comment by danielgorbatov** [comment] 2021-05-24 21:27
Fixed. PR is pending #225.

**Comment by gojko** [comment] 2021-10-18 21:34
thanks, this is now published as v 5.14.0

**Closed by gojko** 2021-10-18 21:34 UTC
