### ISSUE TITLE
Claudia Create fails with errno -4048 on Windows 7

### ISSUE THREAD

**Issue by 18steps** [claudiajs/claudia#110] opened 2017-04-10 11:55 UTC
I'm on Windows 7, following the [Hello World Chatbot tutorial](https://claudiajs.com/tutorials/hello-world-chatbot.html). I run:
 
`claudia create --region eu-central-1 --api-module bot`

Which produces the following output:

```
packaging files npm pack "C:\dev\claudia-bot"
{ Error: EPERM: operation not permitted, rename 'C:\Users\MIKAL~1.MAD\AppData\Local\Temp\07d86c6b-6684-42b9-9851-45fb51400b22\package' -> 'C:\Users\MIKAL~1.MAD\AppData\Local\Temp\e4bac5c0-a04a-42e6-b674-20464851d659'
  errno: -4048,
  code: 'EPERM',
  syscall: 'rename',
  path: 'C:\\Users\\MIKAL~1.MAD\\AppData\\Local\\Temp\\07d86c6b-6684-42b9-9851-4
5fb51400b22\\package',
  dest: 'C:\\Users\\MIKAL~1.MAD\\AppData\\Local\\Temp\\e4bac5c0-a04a-42e6-b674-2
0464851d659' }
```

From what I can tell it has 2 problems:

1. It's trying to rename /parent/child/ to /uncle/
2. It uses absolute paths.

From [this page](https://www.windows-commandline.com/rename-directory-from-command-line/):

> Note that, with rename command, we can’t move the files to another drive or directory. This command just renames the existing file/folder and does not create a new file.  That is why it does not accept full path for the target file name. If you try to do that you will get the error – “The syntax of the command is incorrect.”

I can create similar issues on the command line in several ways:
1. `rename parent\child uncle`
This gives us the folders `/parent` and `/parent/uncle`
2. `rename ./parent/child ./uncle`
Syntax error.
3. `rename .\parent\child .\uncle`
Syntax error.
4. `rename c:\dev\test-rename\parent\child c:\dev\test-rename\uncle`
Syntax error.

Searching the global claudia source files for "packaging files" leads me to believe the problem is with the following piece of code in `<global>/node_modules/claudia/src/tasks/collect-files.js` starting at line 38:

```
copyFiles = function (packageConfig) {
	const packDir = tmppath(),
		targetDir = tmppath(),
		expectedName = expectedArchiveName(packageConfig);
	fsUtil.ensureCleanDir(packDir);
	return runNpm(packDir, 'pack "' + path.resolve(sourcePath) + '"', logger)
	.then(() => extractTarGz(path.join(packDir, expectedName), packDir))
	.then(() => fs.renameAsync(path.join(packDir, 'package'), targetDir))
	.then(() => {
		fsUtil.rmDir(packDir);
		return targetDir;
	});
},
```

Where the salient detail is `fs.renameAsync(path.join(packDir, 'package'), targetDir))`.

After a few attempts I have determined that the correct way to go about this is the following:

`fsUtil.copy(path.join(packDir, 'package','*'), targetDir)`

This copies the files from `<packDir>/package` to `<targetDir>`.

The error is gone and everything works. I will issue a pull request shortly.

**Comment by gojko** [comment] 2017-05-28 20:55
i'm closing this as i've been unable to reproduce it

**Closed by gojko** 2017-05-28 20:55 UTC
