### ISSUE TITLE
concurrent updates causes npm install failures

### ISSUE THREAD

**Issue by zeevl** [claudiajs/claudia#121] opened 2017-05-16 21:38 UTC
I have a project with several claudia configs, i.e. a few lambda functions, a web project, api project etc.  

To speed up deployment I'd like to run them concurrently, however it appears claudia uses the same temp directory for producing the deployment, so running two deployments at the same time causes problems.  Would like to be able to customize the deployment directory, or have it simply use a unique temp dir for each deployment.

* Expected behaviour:
Running `concrrently "claudia update --config lambda1.json" "claudia update --config lambda2.json"` should succeed.

* What actually happens:
One of the tasks (usually) fails on the npm install

**Comment by gojko** [comment] 2017-05-28 20:56
this is not a bug, but if you'd like to submit a pull request that supports parallel work, please do and I'll merge it. closing for now

**Closed by gojko** 2017-05-28 20:56 UTC
